### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by hooperbill** [vandeseer/easytable#39]
Include hyperlink link support for the contents of a cell.

**Comment by hooperbill** [comment]
After some additional research I determined that adding hyperlinks is problematic as the creation of an annotation is required and that annotation is then added to the page. This then requires the caller to keep track of any add annotations and add them to the page after the table is drawn. The table drawer is unable to do this as it only has access to the page content stream and has no direct access to the page.
I have implemented a solution that works for me so I guess this enhancement request could be closed. I am more that happy to share my solution, just ask!

**Comment by vandeseer** [comment]
Hey @hooperbill, thanks for offering to share your solution :+1: 

I am thinking about a `CustomCell` class that would maybe also allow for easier customizations like the one for hyperlinks. It is currently in a feature branch and I'm still not sure about whether the solution is acceptable for releasing ... :smile: 

If there is an easy way to share your solution (e.g. by creating gist, or a pull request etc.) I would be eager to see it!

**Comment by hooperbill** [comment]
I will find a way to share my code. In the mean time I will close this issue.
